# https://taskfile.dev
version: '3'
tasks:
  pc:
    cmds:
      - yamlfmt .
      - actionlint
      - gitleaks protect --staged . --no-banner
  test-*:
    vars:
      EVENT: '{{index .MATCH 0}}'
    cmds:
      - if act {{.EVENT}} --artifact-server-path=/tmp/artifacts -p=false {{.CLI_ARGS}}; then echo "test passed"; else echo "test failed"; fi
