# https://taskfile.dev
version: '3'
tasks:
  pc:
    cmds:
      - yamlfmt .
      - actionlint
      - gitleaks protect --staged . --no-banner
  test:
    cmds:
      - if act workflow_dispatch -p=false {{.CLI_ARGS}}; then echo "test passed"; else echo "test failed"; fi
