name: Deploy Workflow
on:
  push:
    branches:
      - main
jobs:
  create-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Create GitHub Deployment
        env:
          GH_TOKEN: ${{ github.token }}
        run: |-
          gh api repos/${{ github.repository }}/deployments \
            -X POST \
            -F ref=${{ github.ref_name }} \
            -F environment=production \
            -F description="Deployment triggered by push to main" \
            -F auto_merge=false \
            -F required_contexts=[]
