name: Reusable Workflow
on: #  yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      name:
        description: "Name of the person to greet"
        required: true
        type: string
      environment:
        description: "Github Actions Environment"
        required: false
        type: string
jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Preprocess
        run: |
          echo "Plan List"
          echo "- Plan 1"
          echo "- Plan 2"
          echo "- Plan 3"
  greet:
    needs: preprocess
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Greet
        run: |
          echo "Hello, ${{ inputs.name }}!"
          echo "This environment is ${{ inputs.environment }}."
